### ISSUE TITLE
Simplify multimodal user prompt syntax

### ISSUE THREAD

**Issue by nansravn** [GoogleCloudPlatform/promptweaver#14]
# Objective
Simplify the rendering of prompt templates with several images in the user prompt.

## Implementation
Ensure that a `multimodal` composite part can be defined in the prompt template, pointing the PromptFlow render to preprocess the template, extracting and rendering all the respective parts of the prompt automatically.
All the texts, images, videos, audios, documents in the `multimodal` part should be rendered properly before calling Gemini.

> This feature should work with `gs://` or `https://storage.googleapis.com/` URIs listed in the middle of the user prompt text.

## Example 1: multimodal prompt with text and images

```text
# User's home art collection
## Painting #1
gs://cloud-samples-data/generative-ai/image/room-art-1.png
Location: living room

## Painting #2
gs://cloud-samples-data/generative-ai/image/room-art-2.png
Location:: bedroom

## Painting #3
gs://cloud-samples-data/generative-ai/image/room-art-3.png
Location:: bathroom
```

## Example 2: multimodal prompt with text and images

```text
# User's home art collection
## Painting #1
https://storage.googleapis.com/cloud-samples-data/generative-ai/image/room-art-1.png
Location: living room

## Painting #2
https://storage.googleapis.com/cloud-samples-data/generative-ai/image/room-art-2.png
Location:: bedroom

## Painting #3
https://storage.googleapis.com/cloud-samples-data/generative-ai/image/room-art-3.png
Location:: bathroom
```

# Example: PromptWeaver Sample

```yaml
# ---
name: Multimodal Art Advisor
description: This prompt guides the AI to act as a personalized art curator, providing expert advice on how to arrange and display artwork within a user's home.
model:
  model_name: gemini-1.5-pro-002
  generation_config:
    temperature: 0.3
    max_output_tokens: 1000
  system_instruction: |
    You are an AI Art Advisor. You have been provided with information about a user's art collection, including images of the artwork and the rooms where they are currently displayed. 

    Your task is to evaluate the artwork and provide advice on how to best display it in the user's home. This may include:

    * **Analyzing individual pieces:** Consider the style, subject matter, color palette, and overall aesthetic of each artwork.
    * **Assessing the context:**  Take into account the room's function, size, existing decor, and the user's implied preferences based on their collection.
    * **Suggesting placement:** Recommend optimal locations for each piece within the home. Explain how the artwork interacts with the room's atmosphere and purpose.
    * **Offering alternatives:**  If relevant, suggest alternative arrangements or pairings of artwork to enhance the overall aesthetic flow and impact.

    Remember to be:

    * **Descriptive and insightful:** Provide detailed explanations for your recommendations.
    * **Respectful and constructive:** Offer suggestions in a positive and helpful manner.
    * **User-centric:**  Focus on how the art can best serve the user's enjoyment of their living space.
# ---
variables:
  user_question:
    sample: What do you believe of each one of those paintings? Should I swap rooms for any of those paitings?
# ---
user:
  - multimodal: |
      # User's home art collection
      ## Painting #1
      gs://cloud-samples-data/generative-ai/image/room-art-1.png
      Location: living room
      
      ## Painting #2
      gs://cloud-samples-data/generative-ai/image/room-art-2.png
      Location:: bedroom
      
      ## Painting #3
      gs://cloud-samples-data/generative-ai/image/room-art-3.png
      Location:: bathroom

      # Task
      Now, based in the user's art collection, please answer the following question:
      {{ user_question }}
```
